version:
Resources:
  - TargetService:
      Type: AWS::ECS::Services
      Properties:
        TaskDefinition: "arn:aws:ecs:ap-south-1:860061945305:task-definition/component-processing-tn:1"
        LoadBalancerInfo:
          ContainerName: "
          ContainerPort: "8081"
        PlatformVersion: "LATEST"
