version: 0.2


phases:
  install:
    runtime-versions:
      docker: 20
      java: corretto17
  pre_build:
    commands:
      - mvn clean install
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 860061945305.dkr.ecr.ap-south-1.amazonaws.com
      - APPLICATION_NAME=component_processing
      - APPLICATION_VERSION=1.0
      - REPOSITORY_URI=860061945305.dkr.ecr.ap-south-1.amazonaws.com/component_processing:latest
  build:
    commands:
      - echo Build started on `date`
      - echo $IMAGE_NAME
      - mvn clean package -Ddockerfile.skip
      - docker tag $APPLICATION_NAME:$APPLICATION_VERSION $REPOSITORY_URI:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo $(docker images)
      - docker images
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - echo push completed
      - printf '[{"name":"%s","imageUri":"%s"}]' $CONTAINER_NAME $IMAGE_URI > imagedefinitions.json
      - cat imagedefinitions.json
artifacts:
  files: imagedefinitions.json
