version: 0.2


phases:
  install:
    runtime-versions:
      docker: 18
      java: corretto11
  pre_build:
    commands:
      - mvn clean install
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --no-include-email --region $AWS_REGION)
      - APPLICATION_NAME=component_processing
      - APPLICATION_VERSION=1.0
      - REPOSITORY_URI=156962844638.dkr.ecr.ap-south-1.amazonaws.com/ritam_component_processing_registry
  build:
    commands:
      - echo Build started on `date`
      - echo Building Docker image
      - mvn spring-boot:build-image
      - docker tag $APPLICATION_NAME:$APPLICATION_VERSION $REPOSITORY_URI:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Created docker images...
      - docker images
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - echo Writing image definitions file...
      - printf '[{"name":"ritam_component_processing_container","imageUri":"%s"}]' $REPOSITORY_URI:latest > imagedefinitions.json
      - cat imagedefinitions.json
artifacts:
  files: imagedefinitions.json